#unsplash API keys
UNSPLASH_CLIENT_ID = ""
UNSPLASH_CLIENT_SECRET = ""
UNSPLASH_REDIRECT_URI = ""
UNSPLASH_CODE = ""

#twitter API keys
TT_API_KEY = ""
TT_API_SECRET_KEY = ""
TT_ACCESS_TOKEN = ""
TT_ACCESS_TOKEN_SECRET = ""